apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: busybox
    visualize: "true"
  name: busybox
spec:
  deprecatedPublicIPs:
  - 192.168.1.61
  externalIPs:
  - 192.168.1.61
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: busybox
    visualize: "true"
status:
  loadBalancer: {}
