apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cat-service
    visualize: "true"
  name: cat-service
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: cat-service
        tier: backend
        track: stable
        run: cat-service
        visualize: "true"
    spec:
      containers:
      - image: rpicloud/demo-cat-service:dns-0.0.2
        name: cat-service
        livenessProbe:
          httpGet:
            # Path to probe; should be cheap, but representative of typical behavior
            path: /
            port: 80
          initialDelaySeconds: 120
          timeoutSeconds: 1