apiVersion: v1
kind: Service
metadata:
  labels:
    app: dog-service
    tier: backend
    run: dog-service
    visualize: "true"
  name: dog-service
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: dog-service
    tier: backend
