apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-04-24T19:43:12Z
  labels:
    run: gateway-ui
    visualize: "true"
  name: gateway-ui
  namespace: default
  resourceVersion: "3133"
  selfLink: /api/v1/namespaces/default/services/gateway-ui
  uid: c78f3751-0a54-11e6-9f1d-42010af0012a
spec:
  clusterIP: 10.47.244.102
  ports:
  - nodePort: 31986
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: gateway-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}