apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: 2016-04-24T19:15:44Z
  generation: 1
  labels:
    run: config-service
  name: config-service
  namespace: default
  resourceVersion: "2587"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/config-service
  uid: f152780f-0a50-11e6-9f1d-42010af0012a
spec:
  replicas: 1
  selector:
    matchLabels:
      run: config-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: config-service
    spec:
      containers:
      - image: gcr.io/kubernetes-code-lab-1282/demo-config-service:v1
        imagePullPolicy: IfNotPresent
        name: config-service
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}