apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeting-rpi
    run: greeting-rpi
    visualize: "true"
  name: greeting-rpi
spec:
  externalIPs:
  - 192.168.1.81
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: greeting-rpi
